services:
  event_attendence:
    build:
      context: ./app
    depends_on:
      - event_db
      - tracker_db
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  event_db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=events
    volumes:
      - database:/data/db
    ports:
      - 5432:5432

  tracker_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=tracker_data
    ports:
      - 27017:27017
    volumes:
      - tracker_data:/data/db

volumes:
  database:
  tracker_data: