services:
  event_attendence:
    build:
      context: ./app
    depends_on:
      - event_db
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  event_db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=toor
    volumes:
      - database:/data/db
    ports:
      - 5432:5432

volumes:
  database: